[build]
  publish = "dist/public"
  command = "cd client && npx vite build --outDir ../dist/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"