[build]
  publish = "dist/public"
  command = "node enhanced-netlify-build.js"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200